# Generated by Django 5.0 on 2024-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
