# Generated by Django 5.0 on 2024-01-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0006_alter_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
