# Generated by Django 5.0 on 2024-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0007_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
