# Generated by Django 5.0 on 2024-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0009_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
