# Generated by Django 5.0 on 2024-01-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0011_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.CharField(max_length=10000),
        ),
    ]
