# Generated by Django 5.0 on 2024-02-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0012_alter_product_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mail', models.CharField(max_length=25)),
                ('number', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=25)),
            ],
        ),
    ]
