# Generated by Django 5.0 on 2024-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0013_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
