# Generated by Django 5.0 on 2024-02-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0016_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivered',
        ),
    ]
