# Generated by Django 5.0 on 2024-02-20 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0017_remove_cart_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='cart_product_details',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='cart_quantity',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='cart_user_details',
        ),
    ]
