# Generated by Django 5.0 on 2024-02-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0018_rename_products_cart_cart_product_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
