# Generated by Django 5.0 on 2024-02-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0020_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gz.product')),
                ('wishlist_user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gz.user')),
            ],
        ),
    ]
