# Generated by Django 5.0 on 2024-02-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0021_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
