# Generated by Django 5.0 on 2024-02-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0028_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_key',
            new_name='sub_categories',
        ),
    ]
