# Generated by Django 5.0 on 2024-02-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0029_rename_product_key_product_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='original_quantity',
            field=models.IntegerField(),
        ),
    ]
