# Generated by Django 5.0 on 2024-02-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0030_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_categories',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
