# Generated by Django 5.0 on 2024-02-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0031_alter_product_sub_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
    ]
