# Generated by Django 5.0 on 2024-02-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0032_remove_order_last_name_alter_order_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='mail',
            new_name='sub_mail',
        ),
    ]
