# Generated by Django 5.0 on 2024-02-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0033_rename_mail_mail_sub_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='sub_mail',
            new_name='mail',
        ),
    ]
