# Generated by Django 5.0 on 2024-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0034_rename_sub_mail_mail_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlist_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
