# Generated by Django 5.0 on 2024-02-28 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0035_wishlist_wishlist_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
    ]
