# Generated by Django 5.0 on 2024-02-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0037_rename_product_order_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gz.user'),
            preserve_default=False,
        ),
    ]
