# Generated by Django 5.0 on 2024-02-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0038_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
