# Generated by Django 5.0 on 2024-03-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0040_alter_order_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_status',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
