# Generated by Django 5.0 on 2024-03-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0043_remove_order_date_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='instruction',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
