# Generated by Django 5.0 on 2024-03-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0045_alter_order_delivery_date_alter_order_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_status',
            field=models.CharField(default='Payment Pending', max_length=20, null=True),
        ),
    ]
