# Generated by Django 5.0 on 2024-03-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0046_alter_order_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
