# Generated by Django 5.0 on 2024-03-06 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gz', '0047_product_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.AlterField(
            model_name='order',
            name='instruction',
            field=models.CharField(default='Your Order Has Been Successfully Placed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_status',
            field=models.CharField(default='Order Placed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
